# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a706a041dbb4c7c2996ca5e4f0fcb200a392ab386b0677f9fddbee362f06c1e3f59aaf03342548abd618d196d9f31c325973deacbadda44b2c18ac6e931b1ac3

test:
  secret_key_base: bf2e65230e1fb55c1cabc17efd7003f6b7b5d9dd032232927bb3b0500e449ef189d3f61835e21266b46b4d3ae7744845e8657641ce40d7829e15eaa5be2b08eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
